### ISSUE TITLE
Error converting Expo in beta30

### ISSUE THREAD

**Issue by mcallisto** [ScalablyTyped/Converter#270]
I tried to update this bindings library https://github.com/mcallisto/expo-slinky from `beta29` to `beta30`.

While `beta29` compiles, I get the following with `beta30`:

```
[error] /home/***/expo-slinky/target/scala-2.13/src_managed/main/scalablytyped/vision.id.expo.facade/reactNative/mod/ART.scala:9:8: object creation impossible. Missing implementation for:
[error]   def _to: vision.id.expo.facade.reactNative.mod.ART._To // inherited from trait Shortcut
[error] object ART extends Shortcut {
[error]        ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

Any idea why?

**Comment by oyvindberg** [comment]
Hmm, can you try to turn minimization off? If that works it'll be an easy fix

**Comment by mcallisto** [comment]
Yes, it works! Narrowing the search, the issue is with `react-native` that now cannot be minimized.

I added it to minimization:
```
stMinimize := Selection.AllExcept(
  ...,
  "react-native"
)

```

**Comment by mcallisto** [comment]
Hi @oyvindberg I have another issue with the same bindings library.
This happen on both `beta29` and `beta30` on branch https://github.com/mcallisto/expo-slinky/tree/sdk40 where I am trying to implement Expo SDK 40.

Trying to compile I get the following error:

```
[error] java.lang.RuntimeException: TsHelperFile(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/Entitlements.d.ts),FromFolder(InFolder(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins),TsIdentLibraryScoped(expo,config-plugins)),IArray(TsIdentModule(Some(expo),List(config-plugins, build, ios, Entitlements)))) -> Right(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/Entitlements.d.ts): Parse error at 37.16 end of input expected)
[error] TsHelperFile(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/utils/Xcodeproj.d.ts),FromFolder(InFolder(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins),TsIdentLibraryScoped(expo,config-plugins)),IArray(TsIdentModule(Some(expo),List(config-plugins, build, ios, utils, Xcodeproj)))) -> Right(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/utils/Xcodeproj.d.ts): Parse error at 47.16 end of input expected)
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at org.scalablytyped.converter.plugin.ScalablyTypedConverterGenSourcePlugin$.$anonfun$projectSettings$7(ScalablyTypedConverterGenSourcePlugin.scala:124)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (stImport) TsHelperFile(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/Entitlements.d.ts),FromFolder(InFolder(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins),TsIdentLibraryScoped(expo,config-plugins)),IArray(TsIdentModule(Some(expo),List(config-plugins, build, ios, Entitlements)))) -> Right(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/Entitlements.d.ts): Parse error at 37.16 end of input expected)
[error] TsHelperFile(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/utils/Xcodeproj.d.ts),FromFolder(InFolder(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins),TsIdentLibraryScoped(expo,config-plugins)),IArray(TsIdentModule(Some(expo),List(config-plugins, build, ios, utils, Xcodeproj)))) -> Right(InFile(/home/.../expo-slinky/target/scala-2.13/scalajs-bundler/main/node_modules/@expo/config-plugins/build/ios/utils/Xcodeproj.d.ts): Parse error at 47.16 end of input expected)

```

**Comment by oyvindberg** [comment]
Hey there @mcallisto .

Sorry about the silence. I've been working on the minimization issue and have it almost resolved. I don't have any automatic tests for the minimization feature, so I completely forgot about it for the encoding change in beta30. 

For the parsing issue, the issue in `Xcodeproj.d.ts` this line:
```typescript
export declare function isNotTestHost([, sectionItem]: ConfigurationSectionEntry): boolean;
```
I didn't know that was legal syntax, so no surprise the parser doesn't either. Fix forthcoming

**Comment by oyvindberg** [comment]
`stIgnore`ing `@expo/config-plugins` might help for now

**Comment by mcallisto** [comment]
Thank you @oyvindberg for the fix, as soon as I am confident I will update the react-native slinky demo to a newer Expo SDK (currently is at SDK 38, I am at 39 and playing with 40)
