### ISSUE TITLE
Vue.js 3.1 conversion problems

### ISSUE THREAD

**Issue by otobrglez** [ScalablyTyped/Converter#336]
Hey guys!

First. This project is so very impressive. I love it! Thanks for putting the effort into this. I'm playing around with ScalablyTyped and Scala.js and although the ecosystem is new and fresh a lot of stuff works out of the box without any problems. Kudos!

Second. I was hoping to get Scala.js, ScalablyTyped and Vue.js 3.x to somehow work together.

Upon installing the following things:
- Scala.js 1.6.0
- sbt-converter 1.0.0-beta35
- Scala 2.13.6
- SBT 1.5.5
- Snowpack 3.8

I've managed to get things working with a lot of different JS libs,... however when I try to do the `stImport`(`sbt update`...)
I run into following conversion/compilation issue.

```
[warn] Phase1ReadTypescript.scala:198  Processing vue [thread => 136, project => adele-frontend, ms => 51179, path => /Users/otobrglez/Projects/adele/frontend/node_modules/vue, phase => typescript, id => vue]
[warn] Phase2ToScalaJs.scala:64  Processing @babel/types [thread => 136, project => adele-frontend, ms => 51447, phase => scala.js, id => @babel/types]
[warn] Phase2ToScalaJs.scala:64  Processing @babel/parser [thread => 136, project => adele-frontend, ms => 54121, phase => scala.js, id => @babel/parser]
[warn] Phase2ToScalaJs.scala:64  Processing source-map [thread => 136, project => adele-frontend, ms => 54146, phase => scala.js, id => source-map]
[warn] Phase2ToScalaJs.scala:64  Processing @vue/compiler-core [thread => 136, project => adele-frontend, ms => 54172, phase => scala.js, id => @vue/compiler-core]
[warn] Phase2ToScalaJs.scala:64  Processing @vue/reactivity [thread => 136, project => adele-frontend, ms => 54253, phase => scala.js, id => @vue/reactivity]
[warn] Phase2ToScalaJs.scala:64  Processing @vue/runtime-core [thread => 136, project => adele-frontend, ms => 54297, phase => scala.js, id => @vue/runtime-core]
[warn] Phase2ToScalaJs.scala:64  Processing csstype [thread => 136, project => adele-frontend, ms => 54548, phase => scala.js, id => csstype]
[warn] Phase2ToScalaJs.scala:64  Processing @vue/runtime-dom [thread => 136, project => adele-frontend, ms => 55617, phase => scala.js, id => @vue/runtime-dom]
[warn] Phase2ToScalaJs.scala:64  Processing vue [thread => 136, project => adele-frontend, ms => 55808, phase => scala.js, id => vue]
[warn] Phase3Compile.scala:107  Using cached build /Users/otobrglez/.ivy2/local/org.scalablytyped/babel__types_sjs1_2.13/7.14.8-82a270/jars/babel__types_sjs1_2.13.jar [thread => 136, project => adele-frontend, ms => 65534, phase => build, id => @babel/types, flavour => NormalFlavour]
[warn] Phase3Compile.scala:107  Using cached build /Users/otobrglez/.ivy2/local/org.scalablytyped/babel__parser_sjs1_2.13/7.14.8-52c747/jars/babel__parser_sjs1_2.13.jar [thread => 136, project => adele-frontend, ms => 65545, phase => build, id => @babel/parser, flavour => NormalFlavour]
[warn] Phase3Compile.scala:107  Using cached build /Users/otobrglez/.ivy2/local/org.scalablytyped/source-map_sjs1_2.13/0.7.3-067c9b/jars/source-map_sjs1_2.13.jar [thread => 136, project => adele-frontend, ms => 65562, phase => build, id => source-map, flavour => NormalFlavour]
[warn] Phase3Compile.scala:107  Using cached build /Users/otobrglez/.ivy2/local/org.scalablytyped/vue__compiler-core_sjs1_2.13/3.1.5-effaa0/jars/vue__compiler-core_sjs1_2.13.jar [thread => 136, project => adele-frontend, ms => 65636, phase => build, id => @vue/compiler-core, flavour => NormalFlavour]
[warn] Phase3Compile.scala:107  Using cached build /Users/otobrglez/.ivy2/local/org.scalablytyped/vue__reactivity_sjs1_2.13/3.1.5-5bbc71/jars/vue__reactivity_sjs1_2.13.jar [thread => 136, project => adele-frontend, ms => 65649, phase => build, id => @vue/reactivity, flavour => NormalFlavour]
[warn] Phase3Compile.scala:123  Building /Users/otobrglez/.ivy2/local/org.scalablytyped/vue__runtime-core_sjs1_2.13/3.1.5-ef8f24/jars/vue__runtime-core_sjs1_2.13.jar... [thread => 136, project => adele-frontend, ms => 65857, phase => build, id => @vue/runtime-core, flavour => NormalFlavour]
[info] ZincCompiler.scala:234 msg.get() compiling 117 Scala sources to /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/target/scala-2.13/classes ... [project => adele-frontend, ms => 65615]
[error] ZincCompiler.scala:230 msg.get() [Error] /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/src/main/scala/typings/vueRuntimeCore/mod/package.scala:3142: class Array takes type parameters [project => adele-frontend, ms => 72439]
[error] ZincCompiler.scala:230 msg.get() [Error] /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/src/main/scala/typings/vueRuntimeCore/mod/package.scala:3150: class Array takes type parameters [project => adele-frontend, ms => 72452]
[error] ZincCompiler.scala:230 msg.get() two errors found [project => adele-frontend, ms => 72610]
[error] Phase3Compile.scala:147 err Compilation failed: -Xplugin:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.6/1.6.0/scalajs-compiler_2.13.6-1.6.0.jar, -encoding, utf-8, -feature, -g:notailcalls, -language:implicitConversions, -language:higherKinds, -language:existentials, -bootclasspath, /Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar, -classpath, /Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.6/scala-compiler-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.6/scala-reflect-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.19.0/jline-3.19.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.6.0/scalajs-library_2.13-1.6.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.6/1.6.0/scalajs-compiler_2.13.6-1.6.0.jar:/Users/otobrglez/.ivy2/local/org.scalablytyped/vue__reactivity_sjs1_2.13/3.1.5-5bbc71/jars/vue__reactivity_sjs1_2.13.jar:/Users/otobrglez/.ivy2/local/org.scalablytyped/std_sjs1_2.13/4.3-8cb640/jars/std_sjs1_2.13.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-dom_sjs1_2.13/1.1.0/scalajs-dom_sjs1_2.13-1.1.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.0.0/scalajs-library_2.13-1.0.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.5.1/scalajs-library_2.13-1.5.1.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/olvind/scalablytyped-runtime_sjs1_2.13/2.4.2/scalablytyped-runtime_sjs1_2.13-2.4.2.jar [Error] /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/src/main/scala/typings/vueRuntimeCore/mod/package.scala:3142: class Array takes type parameters, [Error] /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/src/main/scala/typings/vueRuntimeCore/mod/package.scala:3150: class Array takes type parameters [thread => 136, project => adele-frontend, ms => 73148, phase => build, id => @vue/runtime-core, flavour => NormalFlavour]
[warn] Phase3Compile.scala:123  Building /Users/otobrglez/.ivy2/local/org.scalablytyped/csstype_sjs1_2.13/2.6.17-d95a28/jars/csstype_sjs1_2.13.jar... [thread => 136, project => adele-frontend, ms => 73995, phase => build, id => csstype, flavour => NormalFlavour]
[info] ZincCompiler.scala:234 msg.get() compiling 562 Scala sources to /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/c/csstype/target/scala-2.13/classes ... [project => adele-frontend, ms => 73527]
[error] ZincCompiler.scala:230 msg.get() two errors found [project => adele-frontend, ms => 73551]
[error] Phase3Compile.scala:147 err Compilation failed: -Xplugin:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.6/1.6.0/scalajs-compiler_2.13.6-1.6.0.jar, -encoding, utf-8, -feature, -g:notailcalls, -language:implicitConversions, -language:higherKinds, -language:existentials, -bootclasspath, /Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar, -classpath, /Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.6/scala-compiler-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.6/scala-reflect-2.13.6.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.19.0/jline-3.19.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.6.0/scalajs-library_2.13-1.6.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.6/1.6.0/scalajs-compiler_2.13.6-1.6.0.jar:/Users/otobrglez/.ivy2/local/org.scalablytyped/std_sjs1_2.13/4.3-8cb640/jars/std_sjs1_2.13.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-dom_sjs1_2.13/1.1.0/scalajs-dom_sjs1_2.13-1.1.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.0.0/scalajs-library_2.13-1.0.0.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.5.1/scalajs-library_2.13-1.5.1.jar:/Users/otobrglez/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/olvind/scalablytyped-runtime_sjs1_2.13/2.4.2/scalablytyped-runtime_sjs1_2.13-2.4.2.jar [Error] /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/src/main/scala/typings/vueRuntimeCore/mod/package.scala:3142: class Array takes type parameters, [Error] /Users/otobrglez/Projects/adele/frontend/target/streams/_global/stImport/_global/streams/sources/v/vue__runtime-core/src/main/scala/typings/vueRuntimeCore/mod/package.scala:3150: class Array takes type parameters [thread => 136, project => adele-frontend, ms => 74090, phase => build, id => csstype, flavour => NormalFlavour]
[error] stack trace is suppressed; run last stImport for the full output
[error] (stImport) FromFolder(InFolder(/Users/otobrglez/Projects/adele/frontend/node_modules/@vue/runtime-core),TsIdentLibraryScoped(vue,runtime-core)) -> Right(Compilation failed: )
[error] FromFolder(InFolder(/Users/otobrglez/Projects/adele/frontend/node_modules/csstype),TsIdentLibrarySimple(csstype)) -> Right(Compilation failed: )
[error] Total time: 74 s (01:14), completed 21 Jul 2021, 15:31:31
```

If you zoom in a bit

```
...
package.scala:3150: class Array takes type parameters
...
```

The source code at the following line looks like this

```scala
  @scala.inline
  def watch_false[T /* <: typings.vueRuntimeCore.mod.MultiWatchSources */, Immediate /* <: scala.Boolean */](
    sources: /* import warning: importer.ImportType#apply c repeated non-array type: T */ Array,
    cb: typings.vueRuntimeCore.mod.WatchCallback[
      typings.vueRuntimeCore.mod.MapSources[T, typings.vueRuntimeCore.vueRuntimeCoreBooleans.`false`], 
      typings.vueRuntimeCore.mod.MapSources[T, Immediate]
    ]
  ): typings.vueRuntimeCore.mod.WatchStopHandle = (typings.vueRuntimeCore.mod.^.asInstanceOf[js.Dynamic].applyDynamic("watch")(sources.asInstanceOf[js.Any], cb.asInstanceOf[js.Any])).asInstanceOf[typings.vueRuntimeCore.mod.WatchStopHandle]

```

In `inThisBuild` I use the following scalac options (if that is even relevant)

```scala
  scalacOptions ++= Seq(
    "-feature",
    "-deprecation",
    "-unchecked",
    "-language:implicitConversions",
    "-language:existentials",
    "-language:dynamics",
    "-Xfatal-warnings",
    "-Xlint:-unused,_",
    "-Ybackend-parallelism", "4",
    "-Ycache-plugin-class-loader:last-modified",
    "-Ycache-macro-class-loader:last-modified",
    "-Xnon-strict-patmat-analysis",
    "-Xlint:-strict-unsealed-patmat",
  ),
```

Is there anything that I could do to "fix" this on my side? Is there something I could do to help you guys address this challenge somehow? Knowing nothing about this codebase I've checked that there are some tests related to vue in Converter - so probably you test if the conversion works for it?

Thank you and thanks for your work on this!

Cheers!

**Comment by otobrglez** [comment]
Since the output above is pretty sh*** I've exported the output of the `sbt last stImport` to a file that I'm attaching here.

- [last_stImport.txt](https://github.com/ScalablyTyped/Converter/files/6856235/last_stImport.txt)

**Comment by oyvindberg** [comment]
Thanks for the report, it was easy to fix

Also, I don't really like or follow Vue, but from my experience writing the [vue2 demo](https://github.com/ScalablyTyped/Demos/blob/master/vue/src/main/scala/demo.scala) you'll probably best consider the generated code a starting point. You can use it in an untyped manner without too much hassle (like in the demo), but typing this in a safe and practical manner will likely require significant amount of research

**Comment by oyvindberg** [comment]
You can test a snapshot with version `1.0.0-beta35+8-e016cbca-SNAPSHOT` with this resolver
`resolvers += MavenRepository("sonatype-s01-snapshots", "https://s01.oss.sonatype.org/content/repositories/snapshots")`

**Comment by otobrglez** [comment]
Thank you so much @oyvindberg!

**Comment by otobrglez** [comment]
@oyvindberg ; I gave the new build ago... it now crashes spectacularly, but in a different way. 😅 

```
Reference to undefined setting:

  frontend / stPrivateWithin from frontend / stConversionOptions ((org.scalablytyped.converter.plugin.ScalablyTypedPluginBase.projectSettings) ScalablyTypedPluginBase.scala:76)

        at sbt.internal.util.Init.Uninitialized(Settings.scala:419)
        at sbt.internal.util.Init.Uninitialized$(Settings.scala:406)
        at sbt.Def$.Uninitialized(Def.scala:24)
        at sbt.internal.util.Init.delegate(Settings.scala:313)
        at sbt.internal.util.Init.delegate$(Settings.scala:275)
        at sbt.Def$.delegate(Def.scala:24)
        at sbt.internal.util.Init.compiled(Settings.scala:200)
        at sbt.internal.util.Init.compiled$(Settings.scala:187)
        at sbt.Def$.compiled(Def.scala:24)
        at sbt.internal.util.Init.makeWithCompiledMap(Settings.scala:217)
        at sbt.internal.util.Init.makeWithCompiledMap$(Settings.scala:212)
        at sbt.Def$.makeWithCompiledMap(Def.scala:24)
        at sbt.internal.Load$.$anonfun$apply$5(Load.scala:263)
        at sbt.internal.Load$.timed(Load.scala:1393)
        at sbt.internal.Load$.apply(Load.scala:255)
        at sbt.internal.Load$.defaultLoad(Load.scala:56)
        at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
        at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
        at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
        at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
        at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
        at sbt.Command$.process(Command.scala:189)
        at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:278)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:163)
        at sbt.MainLoop$.run(MainLoop.scala:144)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
        at scala.Option.getOrElse(Option.scala:189)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:278)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.process$1(MainLoop.scala:245)
        at sbt.MainLoop$.processCommand(MainLoop.scala:278)
        at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
        at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
        at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
        at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
        at sbt.MainLoop$.next(MainLoop.scala:163)
        at sbt.MainLoop$.run(MainLoop.scala:144)
        at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
        at sbt.io.Using.apply(Using.scala:27)
        at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
        at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
        at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
        at sbt.MainLoop$.runLogged(MainLoop.scala:42)
        at sbt.StandardMain$.runManaged(Main.scala:218)
        at sbt.xMain$.$anonfun$run$11(Main.scala:133)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withIn(Console.scala:230)
        at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
        at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withOut(Console.scala:167)
        at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at scala.Console$.withErr(Console.scala:196)
        at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
        at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
        at sbt.xMain$.withStreams$1(Main.scala:87)
        at sbt.xMain$.run(Main.scala:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
        at sbt.xMain.run(Main.scala:46)
        at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:131)
        at xsbt.boot.Launch$.run(Launch.scala:111)
        at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
        at xsbt.boot.Launch$.launch(Launch.scala:120)
        at xsbt.boot.Launch$.apply(Launch.scala:20)
        at xsbt.boot.Boot$.runImpl(Boot.scala:56)
        at xsbt.boot.Boot$.main(Boot.scala:18)
        at xsbt.boot.Boot.main(Boot.scala)
[error] Reference to undefined setting:
[error]
[error]   frontend / stPrivateWithin from frontend / stConversionOptions ((org.scalablytyped.converter.plugin.ScalablyTypedPluginBase.projectSettings) ScalablyTypedPluginBase.scala:76)
[error]
[error] Use 'last' for the full log.
```

Any ideas?

**Comment by oyvindberg** [comment]
Oh, alright! A feature i just added without testing the plugin. I'll fix it soon and publish a new snapshot
