### ISSUE TITLE
Parse error  ''}'' expected but '{' found

### ISSUE THREAD

**Issue by AlexITC** [ScalablyTyped/Converter#342]
While dealing with an internal library, I got a weird problem generating the Scala.js facade from the TypeScript definitions, initially I thought it was related to #316 but after upgrading scalablytyped, the error persists.

The stacktrace is:

```
[error] java.lang.RuntimeException: TsHelperFile(InFile(/home/dell/example/target/scala-2.13/scalajs-bundler/main/node_modules/@custom-provider/sdk/extras.d.ts),FromFolder(InFolder(/home/dell/example/target/scala-2.13/scalajs-bundler/main/node_modules/@custom-provider/sdk),TsIdentLibraryScoped(custom-provider,sdk)),IArray(TsIdentModule(Some(custom-provider),List(sdk)), TsIdentModule(Some(custom-provider),List(sdk, extras)))) -> Right(Parse error at 7743.25 ''}'' expected but '{' found)
[error]     at scala.sys.package$.error(package.scala:30)
[error]     at org.scalablytyped.converter.plugin.ScalablyTypedConverterPlugin$.$anonfun$stImportTask$7(ScalablyTypedConverterPlugin.scala:85)
[error]     at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]     at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]     at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]     at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]     at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]     at sbt.Execute.work(Execute.scala:291)
[error]     at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]     at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]     at java.base/java.lang.Thread.run(Thread.java:829)
```

The problematic TypeScript parsing seems to be at the `{` from `class Field {` below:

```
readonly X: {
} & JsonFields.Field;
class Field {
    private constructor();
    readonly field: string;
}
```

Any help is appreciated, thanks!

**Comment by oyvindberg** [comment]
Hi there

What's this syntax? Top-level readonly X: ...`? Is that allowed without `const` or similar now?

**Comment by AlexITC** [comment]
Apparently, it is ([ref](https://www.typescriptlang.org/docs/handbook/2/classes.html#readonly))

**Comment by oyvindberg** [comment]
Inside a class yes, then it's a field declaration, but at the top-level I don't think it's allowed?

Note that this is probably easy enough to fix in the parser, and you can unblock yourself by changing the typescript defs inside `node_modules`.

If you want to try to fix the ST parser try to add a test case in `ParserTests.scala`. then you can figure out exactly what doesn't parse

**Comment by AlexITC** [comment]
I should have pasted the whole snippet:

```typescript
export namespace namespacex {
    const CompanionX: {
        fromString(value: string): ContentX;
        readonly JsonFields: {
            readonly OtherX: {
            } & JsonFields.Field;
            class Field {
                private constructor();
                readonly field: string;
            }
        };
    };
}
```

I'm unsure whether that's valid but I'll check it later, this is generated code from Kotlin Multiplatform.

Thanks for the hints.

**Comment by oyvindberg** [comment]
Weirder and weirder - a class within an object type. I can how this resembles a kotlin companion object and it's probably a one to one translation. Before you do anything else with ST I recommend you try to use it from TS first and see if accepts this code.

**Comment by AlexITC** [comment]
Bug filled, thanks!

https://youtrack.jetbrains.com/issue/KT-48493
