### ISSUE TITLE
keys defined with the same name but different types

### ISSUE THREAD

**Issue by bblfish** [ScalablyTyped/Converter#362]
I am  building a project `rdflibTypes` that uses `ScalablyTypedConverterGenSourcePlugin` to build [rdflib.js](https://github.com/linkeddata/rdflib.js/tree/main/src), and then another project  in the same GitHub repo using `ScalablyTypedConverterPlugin` that uses the previously created project to build another library `rdflibScratch`.

When both projects are available in the same sbt file I get the error below. If I remove one of the projects the problem disappears, and I was able to use the initially generated jar.

```scala
[info] resolving key references (10474 settings) ...
java.lang.RuntimeException: Some keys were defined with the same name but different types: 'stImport' (sbt.Task[scala.collection.Seq[java.io.File]], sbt.Task[scala.Tuple2[org.scalablytyped.converter.internal.ImportTypings$Input, org.scalablytyped.converter.internal.ImportTypings$Output]])
	at scala.sys.package$.error(package.scala:30)
	at sbt.internal.Index$.stringToKeyMap0(EvaluateConfigurations.scala:375)
	at sbt.internal.Index$.stringToKeyMap(EvaluateConfigurations.scala:359)
	at sbt.internal.Load$.structureIndex(Load.scala:334)
	at sbt.internal.Load$.$anonfun$apply$8(Load.scala:268)
	at sbt.internal.Load$.timed(Load.scala:1393)
	at sbt.internal.Load$.apply(Load.scala:268)
	at sbt.internal.Load$.defaultLoad(Load.scala:56)
	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:959)
	at sbt.BuiltinCommands$.doLoadProject(Main.scala:959)
	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:912)
	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:150)
	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:145)
	at sbt.Command$.process(Command.scala:189)
	at sbt.MainLoop$.$anonfun$processCommand$5(MainLoop.scala:245)
	at scala.Option.getOrElse(Option.scala:189)
	at sbt.MainLoop$.process$1(MainLoop.scala:245)
	at sbt.MainLoop$.processCommand(MainLoop.scala:278)
	at sbt.MainLoop$.$anonfun$next$5(MainLoop.scala:163)
	at sbt.State$StateOpsImpl$.runCmd$1(State.scala:289)
	at sbt.State$StateOpsImpl$.process$extension(State.scala:325)
	at sbt.MainLoop$.$anonfun$next$4(MainLoop.scala:163)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
	at sbt.MainLoop$.next(MainLoop.scala:163)
	at sbt.MainLoop$.run(MainLoop.scala:144)
	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:119)
	at sbt.io.Using.apply(Using.scala:27)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:112)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:66)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:51)
	at sbt.MainLoop$.runLogged(MainLoop.scala:42)
	at sbt.StandardMain$.runManaged(Main.scala:218)
	at sbt.xMain$.$anonfun$run$11(Main.scala:133)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withIn(Console.scala:230)
	at sbt.internal.util.Terminal$.withIn(Terminal.scala:569)
	at sbt.internal.util.Terminal$.$anonfun$withStreams$1(Terminal.scala:350)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at sbt.internal.util.Terminal$.$anonfun$withOut$2(Terminal.scala:559)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at sbt.internal.util.Terminal$.withOut(Terminal.scala:559)
	at sbt.internal.util.Terminal$.withStreams(Terminal.scala:350)
	at sbt.xMain$.withStreams$1(Main.scala:87)
	at sbt.xMain$.run(Main.scala:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:56)
	at sbt.xMain.run(Main.scala:46)
	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
	at xsbt.boot.Launch$.run(Launch.scala:149)
	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
	at xsbt.boot.Launch$.launch(Launch.scala:159)
	at xsbt.boot.Launch$.apply(Launch.scala:44)
	at xsbt.boot.Launch$.apply(Launch.scala:21)
	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
	at xsbt.boot.Boot$.run(Boot.scala:73)
	at xsbt.boot.Boot$.main(Boot.scala:21)
	at xsbt.boot.Boot.main(Boot.scala)
[error] Some keys were defined with the same name but different types: 'stImport' (sbt.Task[scala.collection.Seq[java.io.File]], sbt.Task[scala.Tuple2[org.scalablytyped.converter.internal.ImportTypings$Input, org.scalablytyped.converter.internal.ImportTypings$Output]])
```

I'll commit the code with a link to this issue.

I guess as a workaround I could move the first library to its own repository, but I thought I'd point this out here.

**Comment by oyvindberg** [comment]
This doesn't work by design. One of the plugins is for creating libraries you want to distribute, and the other is for creating an app. Hopefully the docs can clear this up somewhat.

If you really need both somehow separate out the thing that uses source gen plugin into its own build
