### ISSUE TITLE
Error when convert @chakra-ui/react

### ISSUE THREAD

**Issue by btobolaski** [ScalablyTyped/Converter#384]
I presume that they're doing something unexpected which results in a failure. The stacktrace doesn't help me determine what the cause of the error is:

```
[warn] Phase1ReadTypescript.scala:196  Processing @chakra-ui/react [thread => 173, project => spa, ms => 14647, path => /home/brendan/src/tokenize/spa/target/scala-2.13/scalajs-bundler/main/node_modules/@chakra-ui/react, phase => typescript, id => @chakra-ui/react]
[error] PhaseRes.scala:78  Caught exception: Expected code path [thread => 173, project => spa, ms => 14647, phase => typescript, id => @chakra-ui/react]java.lang.RuntimeException: Expected code path
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at org.scalablytyped.converter.internal.ts.CodePath.$anonfun$forceHasPath$1(CodePath.scala:6)
[error] 	at scala.Option.getOrElse(Option.scala:189)
[error] 	at org.scalablytyped.converter.internal.ts.CodePath.forceHasPath(CodePath.scala:6)
[error] 	at org.scalablytyped.converter.internal.ts.CodePath.forceHasPath$(CodePath.scala:5)
[error] 	at org.scalablytyped.converter.internal.ts.CodePath$NoPath$.forceHasPath(CodePath.scala:30)
[error] 	at org.scalablytyped.converter.internal.ts.modules.MoveGlobals$.apply(MoveGlobals.scala:39)
[error] 	at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript$.$anonfun$Pipeline$13(Phase1ReadTypescript.scala:250)
[error] 	at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.$anonfun$apply$28(Phase1ReadTypescript.scala:211)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[error] 	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[error] 	at scala.collection.immutable.List.foldLeft(List.scala:91)
[error] 	at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.$anonfun$apply$18(Phase1ReadTypescript.scala:211)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRes.map(PhaseRes.scala:19)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRes.map$(PhaseRes.scala:17)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRes$Ok.map(PhaseRes.scala:33)
[error] 	at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.apply(Phase1ReadTypescript.scala:164)
[error] 	at org.scalablytyped.converter.internal.importer.Phase1ReadTypescript.apply(Phase1ReadTypescript.scala:22)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$4(PhaseRunner.scala:71)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$3(PhaseRunner.scala:71)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRes.flatMap(PhaseRes.scala:26)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRes.flatMap$(PhaseRes.scala:24)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRes$Ok.flatMap(PhaseRes.scala:33)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:70)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:47)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:47)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.$anonfun$doNext$1(PhaseRunner.scala:47)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseCache.getOrElse(PhaseCache.scala:26)
[error] 	at org.scalablytyped.converter.internal.phases.PhaseRunner$.apply(PhaseRunner.scala:47)
[error] 	at org.scalablytyped.converter.internal.ImportTypings$.$anonfun$apply$5(ImportTypings.scala:126)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:943)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:943)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at org.scalablytyped.converter.internal.ImportTypings$.apply(ImportTypings.scala:126)
[error] 	at org.scalablytyped.converter.plugin.ScalablyTypedConverterPlugin$.$anonfun$stImportTask$6(ScalablyTypedConverterPlugin.scala:70)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error]
```

Given chakra-ui's typescript definitions, it might have something to do with these 
```
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/accordion [thread => 171, project => spa, ms => 756, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/alert [thread => 171, project => spa, ms => 756, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/avatar [thread => 171, project => spa, ms => 757, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/breadcrumb [thread => 171, project => spa, ms => 757, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/button [thread => 171, project => spa, ms => 757, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/checkbox [thread => 171, project => spa, ms => 758, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/close-button [thread => 171, project => spa, ms => 758, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/control-box [thread => 171, project => spa, ms => 758, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/counter [thread => 171, project => spa, ms => 758, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/css-reset [thread => 171, project => spa, ms => 759, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/editable [thread => 171, project => spa, ms => 759, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/form-control [thread => 171, project => spa, ms => 759, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/hooks [thread => 171, project => spa, ms => 759, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/icon [thread => 171, project => spa, ms => 760, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/image [thread => 171, project => spa, ms => 760, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/input [thread => 171, project => spa, ms => 760, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/layout [thread => 171, project => spa, ms => 761, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/live-region [thread => 171, project => spa, ms => 761, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/media-query [thread => 171, project => spa, ms => 761, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/menu [thread => 171, project => spa, ms => 762, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/modal [thread => 171, project => spa, ms => 762, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/number-input [thread => 171, project => spa, ms => 762, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/pin-input [thread => 171, project => spa, ms => 762, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/popover [thread => 171, project => spa, ms => 763, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/popper [thread => 171, project => spa, ms => 763, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/portal [thread => 171, project => spa, ms => 763, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/progress [thread => 171, project => spa, ms => 764, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/provider [thread => 171, project => spa, ms => 764, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/radio [thread => 171, project => spa, ms => 764, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/react-env [thread => 171, project => spa, ms => 764, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/select [thread => 171, project => spa, ms => 765, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/skeleton [thread => 171, project => spa, ms => 765, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/slider [thread => 171, project => spa, ms => 765, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/spinner [thread => 171, project => spa, ms => 765, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/stat [thread => 171, project => spa, ms => 766, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/switch [thread => 171, project => spa, ms => 766, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/system [thread => 171, project => spa, ms => 766, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/table [thread => 171, project => spa, ms => 766, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/tabs [thread => 171, project => spa, ms => 767, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/tag [thread => 171, project => spa, ms => 767, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/textarea [thread => 171, project => spa, ms => 767, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/theme [thread => 171, project => spa, ms => 767, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/toast [thread => 171, project => spa, ms => 768, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/tooltip [thread => 171, project => spa, ms => 768, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/transition [thread => 171, project => spa, ms => 768, phase => typescript, id => @chakra-ui/react]
[warn] Phase1ReadTypescript.scala:159  Could not find typescript definitions for dependency @chakra-ui/visually-hidden [thread => 171, project => spa, ms => 768, phase => typescript, id => @chakra-ui/react]
``` 

So what can I do to look into this further?

**Comment by btobolaski** [comment]
Small update on this, it appears that the dependencies aren't recursively resolved with ScalaJSBundler. After manually fixing that (painfully), I now have issue with duplicate definitions after type erasure which I assume is related to #368 i.e.

```
[info] ZincCompiler.scala:234 msg.get() compiling 4 Scala sources to /home/brendan/src/tokenize/spa/target/streams/_global/stImport/_global/streams/sources/c/chakra-ui__provider/target/scala-2.13/classes ... [project => spa, ms => 21524]
[error] ZincCompiler.scala:230 msg.get() one error found [project => spa, ms => 21534]
[error] Phase3Compile.scala:147 err Compilation failed: -Xplugin:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.6/1.6.0/scalajs-compiler_2.13.6-1.6.0.jar, -encoding, utf-8, -feature, -g:notailcalls, -language:implicitConversions, -language:higherKinds, -language:existentials, -bootclasspath, /home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.6/scala-library-2.13.6.jar, -classpath, /home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.6/scala-compiler-2.13.6.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.6/scala-reflect-2.13.6.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.19.0/jline-3.19.0.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.6.0/scalajs-library_2.13-1.6.0.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.13.6/1.6.0/scalajs-compiler_2.13.6-1.6.0.jar:/home/brendan/.ivy2/local/org.scalablytyped/chakra-ui__color-mode_sjs1_2.13/1.3.2-cd8ff2/jars/chakra-ui__color-mode_sjs1_2.13.jar:/home/brendan/.ivy2/local/org.scalablytyped/std_sjs1_2.13/4.3-439804/jars/std_sjs1_2.13.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-dom_sjs1_2.13/1.2.0/scalajs-dom_sjs1_2.13-1.2.0.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/com/olvind/scalablytyped-runtime_sjs1_2.13/2.4.2/scalablytyped-runtime_sjs1_2.13-2.4.2.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.0.0/scalajs-library_2.13-1.0.0.jar:/home/brendan/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-js/scalajs-library_2.13/1.5.1/scalajs-library_2.13-1.5.1.jar [Error] /home/brendan/src/tokenize/spa/target/streams/_global/stImport/_global/streams/sources/c/chakra-ui__descendant/src/main/scala/typings/chakraUiDescendant/descendantMod.scala:62: double definition:
[error] def register(nodeOrOptions: T): Unit | scala.scalajs.js.Function1[T | Null,Unit] at line 61 and
[error] def register(nodeOrOptions: typings.chakraUiDescendant.descendantMod.DescendantOptions[K]): Unit | scala.scalajs.js.Function1[T | Null,Unit] at line 62
[error] have same type after erasure: (nodeOrOptions: Object): scala.scalajs.js.| [thread => 143, project => spa, ms => 21672, phase => build, id => @chakra-ui/provider, flavour => NormalFlavour]
```

Is there something that I can do to handle this?

**Comment by oyvindberg** [comment]
I just tried with newest master of the Converter, and newest version of `typescript`, `@types/react`, `@chakra/react`, as installed by `yarn install`.

It did compile successfully
```
Successfully converted @chakra-ui/radio, @chakra-ui/toast, @chakra-ui/transition, @chakra-ui/avatar, std, @chakra-ui/progress, @chakra-ui/react, @chakra-ui/react-utils, @chakra-ui/accordion, scheduler, @chakra-ui/pin-input, @chakra-ui/form-control, @chakra-ui/checkbox, @chakra-ui/styled-system, @chakra-ui/icon, @chakra-ui/color-mode, @chakra-ui/stat, @chakra-ui/theme, @chakra-ui/portal, @chakra-ui/tag, @chakra-ui/spinner, @chakra-ui/select, @chakra-ui/theme-tools, @chakra-ui/number-input, @chakra-ui/skeleton, @chakra-ui/table, @chakra-ui/descendant, @chakra-ui/popper, @ctrl/tinycolor, @chakra-ui/menu, @chakra-ui/react-env, @chakra-ui/popover, @chakra-ui/close-button, @chakra-ui/textarea, @chakra-ui/media-query, css-box-model, @chakra-ui/button, @chakra-ui/utils, react, @chakra-ui/hooks, @chakra-ui/modal, @chakra-ui/alert, @chakra-ui/tooltip, @chakra-ui/layout, @chakra-ui/input, @chakra-ui/counter, @chakra-ui/provider, csstype, @chakra-ui/tabs, @chakra-ui/editable, @chakra-ui/breadcrumb, @chakra-ui/image, @chakra-ui/system, @chakra-ui/switch, @chakra-ui/slider, @chakra-ui/control-box, prop-types
To use in sbt: 
libraryDependencies ++= Seq(
  "org.scalablytyped" %%% "chakra-ui__react" % "1.7.2-76bb8f",
  "org.scalablytyped" %%% "react" % "17.0.37-54f79f"
)
```

On the plus side it did produce many components. On the minus side you'll find that many of them rely on what is currently too fancy typing techniques to produce very useful output. Same issue as #208

**Comment by oyvindberg** [comment]
As such I'll close this and defer it to #208 . On the bright side, there is a solution on the horizon now, which will finally enable us to use react component libraries like this :)
