### ISSUE TITLE
React typings fail to compile

### ISSUE THREAD

**Issue by nikololiahim** [ScalablyTyped/Converter#427]
#### `build.sbt`
```scala
import scala.sys.process._

ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "3.1.0"

lazy val root = project
  .in(file("."))
  .enablePlugins(ScalablyTypedConverterExternalNpmPlugin)
  .settings(
    externalNpm := {
      Process("npm install", baseDirectory.value).!
      baseDirectory.value
    }
  )
  .enablePlugins(ScalaJSPlugin)
  .settings(
    scalaJSUseMainModuleInitializer := true,
    scalaJSLinkerConfig ~= { _.withModuleKind(ModuleKind.ESModule) },
    libraryDependencies ++= Seq(
      "com.github.japgolly.scalajs-react" %%% "core" % "2.0.1",
      "org.scala-js" %%% "scalajs-dom" % "2.1.0",
    ),
  )
```

#### `project/plugins.sbt`
```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.9.0")
addSbtPlugin("org.scalablytyped.converter" % "sbt-converter" % "1.0.0-beta37")
```

#### `src/main/scala/Main.scala`
```scala
@main def hello: Unit = println("hello")
```

### Command (in the terminal):
```
sbt fastLinkJS
```

## Error:
```
[error]   typings.react.mod.ReactFragment
[error]  | typings.react.mod.ReactPortal | Boolean] of type ReactNode refers back to the type itself, Error, Optional[-- [E140] Cyclic Error: /home/nikololiahim/scala/bugs/scalablytyped/target/streams/_global/stImport/_global/streams/sources/r/react/src/main/scala/typings/react/mod/package.scala:937:5 
[error] 937 |type ReactNode = js.UndefOr[
[error]     |     ^
[error]     |illegal cyclic type reference: alias scala.scalajs.js.UndefOr[typings.react.mod.ReactChild | 
[error]     |  typings.react.mod.ReactFragment
[error]     | | typings.react.mod.ReactPortal | Boolean] of type ReactNode refers back to the type itself]) [thread => 188, project => root, ms => 92188, phase => build, id => react, flavour => NormalFlavour]
[error] java.lang.RuntimeException: FromFolder(InFolder(/home/nikololiahim/scala/bugs/scalablytyped/node_modules/@types/react),TsIdentLibrarySimple(react)) -> Right(Compilation failed:   typings.react.mod.ReactFragment)
[error]         at scala.sys.package$.error(package.scala:30)
[error]         at org.scalablytyped.converter.plugin.ScalablyTypedConverterExternalNpmPlugin$.$anonfun$stImportTask$6(ScalablyTypedConverterExternalNpmPlugin.scala:87)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (stImport) FromFolder(InFolder(/home/nikololiahim/scala/bugs/scalablytyped/node_modules/@types/react),TsIdentLibrarySimple(react)) -> Right(Compilation failed:   typings.react.mod.ReactFragment)
[error] Total time: 92 s (01:32), completed Mar 13, 2022 4:29:44 PM
```

## Expectation:
The code compiles successfully.

## Question:
Is there a way to avoid the need to compile react typings if I don't use them directly? For example, if I use react as a dependency to `scalajs-react`.

**Comment by oyvindberg** [comment]
Hey there.

This seems to be the same as #416 . I couldn't repro this on the command line, so I'll dig into it at some later point.

For now a workaround is to configure the converter with a react flavour. that way it'll replace the reference to react node with another type, and things will be fine. 

So, for your question it depends a bit on what you're trying to accomplish. If you don't use react typings at all (inclusive in transitive typescript dependencies) you can just not add the `@types/react` package. you may have to `stIgnore` react it as well since ST expects type definitions for all the npm libraries.

if you have added any typescript react libraries you really should check out the scalajs-react flavour as it generates very useful boilerplate.

**Comment by nikololiahim** [comment]
@oyvindberg Thank you for answer! I'll with different react flavors (should have spent more time reading docs). Closing since this is a duplicate.
