### ISSUE TITLE
stImport error of NotDirectoryException due to .DS_Store file on Mac

### ISSUE THREAD

**Issue by manuzhang** [ScalablyTyped/Converter#431]
It looks `stImport` failed due to [.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) file on Mac. My sbt-converter version is "1.0.0-beta37".
```
[error] java.nio.file.NotDirectoryException: /Users/tianlzhang/git/myovercast/js/target/scala-2.13/scalajs-bundler/main/node_modules/@ant-design/.DS_Store
[error]         at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:406)
[error]         at java.nio.file.Files.newDirectoryStream(Files.java:457)
[error]         at os.walk$stream$$anon$2.generate(ListOps.scala:223)
[error]         at geny.Generator$Mapped.generate(Generator.scala:283)
[error]         at geny.Generator.find(Generator.scala:56)
[error]         at geny.Generator.find$(Generator.scala:54)
[error]         at geny.Generator$Mapped.find(Generator.scala:281)
[error]         at geny.Generator.exists(Generator.scala:65)
[error]         at geny.Generator.exists$(Generator.scala:65)
[error]         at geny.Generator$Mapped.exists(Generator.scala:281)
[error]         at org.scalablytyped.converter.internal.importer.Source$.hasTypescriptSources(Source.scala:26)
[error]         at org.scalablytyped.converter.internal.importer.Source.hasSources(Source.scala:21)
[error]         at org.scalablytyped.converter.internal.importer.Source.hasSources$(Source.scala:20)
[error]         at org.scalablytyped.converter.internal.importer.Source$FromFolder.hasSources(Source.scala:50)
[error]         at org.scalablytyped.converter.internal.importer.Bootstrap$.$anonfun$forFolder$4(Bootstrap.scala:115)
[error]         at org.scalablytyped.converter.internal.importer.Bootstrap$.$anonfun$forFolder$4$adapted(Bootstrap.scala:115)
[error]         at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:304)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[error]         at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
[error]         at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:303)
[error]         at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:297)
[error]         at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:108)
[error]         at scala.collection.TraversableLike.filter(TraversableLike.scala:395)
[error]         at scala.collection.TraversableLike.filter$(TraversableLike.scala:395)
[error]         at scala.collection.AbstractTraversable.filter(Traversable.scala:108)
[error]         at org.scalablytyped.converter.internal.importer.Bootstrap$.forFolder(Bootstrap.scala:115)
[error]         at org.scalablytyped.converter.internal.importer.Bootstrap$.$anonfun$findSources$1(Bootstrap.scala:98)
[error]         at org.scalablytyped.converter.internal.importer.Bootstrap$.findSources(Bootstrap.scala:95)
[error]         at org.scalablytyped.converter.internal.importer.Bootstrap$.fromNodeModules(Bootstrap.scala:84)
[error]         at org.scalablytyped.converter.internal.ImportTypings$.apply(ImportTypings.scala:70)
[error]         at org.scalablytyped.converter.plugin.ScalablyTypedConverterPlugin$.$anonfun$stImportTask$6(ScalablyTypedConverterPlugin.scala:70)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error]         at sbt.Execute.work(Execute.scala:291)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (frontend / stImport) java.nio.file.NotDirectoryException: /Users/tianlzhang/git/myovercast/js/target/scala-2.13/scalajs-bundler/main/node_modules/@ant-design/.DS_Store
```

**Comment by oyvindberg** [comment]
Hey, thanks for the report (and sorry late answer)

Seems like the hole in the directory traversal logic is [here](https://github.com/ScalablyTyped/Converter/blob/master/importer-portable/src/main/scala/org/scalablytyped/converter/internal/importer/Bootstrap.scala#L112), it's missing a `collect { case dir if os.isDir(dir) => dir }` for the `@types` directory case.
