### ISSUE TITLE
StackOverflowError (FollowAliases)

### ISSUE THREAD

**Issue by FabioPinheiro** [ScalablyTyped/Converter#454]
Found a StackOverflowError when using the "ts-jose" library. 
I'm just reporting (I'm not really using this library so I did not investigate much)
Does not seems related with #412
 
 ```
 Scala 3.1.3
 "sbt-converter" % "1.0.0-beta38"
 "ts-jose" -> "4.8.3"
 ```
 
 ```
[error] PhaseRes.scala:81  StackOverflowError [thread => 275, project => did, ms => 20012, phase => typescript, id => ts-jose]java.lang.StackOverflowError
...
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$.apply(FollowAliases.scala:10)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$.$anonfun$apply$3(FollowAliases.scala:19)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$.apply(FollowAliases.scala:19)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$$anonfun$apply$1.applyOrElse(FollowAliases.scala:12)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$.apply(FollowAliases.scala:10)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$.$anonfun$apply$3(FollowAliases.scala:19)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$.apply(FollowAliases.scala:19)
[error] 	at org.scalablytyped.converter.internal.ts.FollowAliases$$anonfun$apply$1.applyOrElse(FollowAliases.scala:12)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
...
  ```
  
*** UPDATE ***
I was also using the library `"jose" -> "1.18.2"` at the same time.
For some reason I was convinced with it didn't had typescript.
Both libraries should have +- the same typescript definitions. 

I'm not investigating further. I'm fine with closing the issue for now and reopen if needed.

**Comment by oyvindberg** [comment]
Hey there, didn't see this until now.

I tried:
```
yarn add typescript jose ts-jose
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
├─ jose@4.8.3
├─ ts-jose@4.8.3
└─ typescript@4.7.4
info All dependencies
├─ jose@4.8.3
├─ ts-jose@4.8.3
└─ typescript@4.7.4
✨  Done in 2.50s.
⌁73% [oyvind:~/scalablytyped] 3s $ stc
```
And got
```
Successfully converted jose, std, ts-jose
To use in sbt: 
libraryDependencies ++= Seq(
  "org.scalablytyped" %%% "jose" % "4.8.3-3fe5e7",
  "org.scalablytyped" %%% "ts-jose" % "4.8.3-15af6a"
)
```

I guess having an older version of the library on the "classpath" makes it quite random what will happen in the end :)

**Comment by FabioPinheiro** [comment]
Seems like something else may have provoked the error.
Thank you for having a look!
