### ISSUE TITLE
Fail to create typings for pixi.js 6.5.2

### ISSUE THREAD

**Issue by lgirault** [ScalablyTyped/Converter#471]
I get the following error when I add  `"pixi.js" -> "6.5.2"` to my npmDependencies:
```
[error] 70 |         with typings.pixiUtils.mod.^[EventTypes, Context]
[error]    |              ^^^^^^^^^^^^^^^^^^^^^^^
[error]    |              type ^ is not a member of object typings.pixiUtils.mod]) [thread => 219, project => leval, ms => 82644, phase => build, id => pixi.js, flavour => NormalFlavour]
[error] java.lang.RuntimeException: FromFolder(InFolder(/home/lgirault/dev/perso/leval/js/target/scala-3.1.3/scalajs-bundler/main/node_modules/pixi.js),TsIdentLibrarySimple(pixi.js)) -> Right(Compilation failed: 70 |         with typings.pixiUtils.mod.^[EventTypes, Context])
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at org.scalablytyped.converter.plugin.ScalablyTypedConverterPlugin$.$anonfun$stImportTask$6(ScalablyTypedConverterPlugin.scala:81)
```
The minimized test-case can be found here : 
https://github.com/ScalablyTyped/Converter/pull/473

**Comment by lgirault** [comment]
ok, I had some trouble to reproduce the bug because I tried to be smart while importing the files from my node_modules. In the end by just copy/pasting it, the bug is reproduced :tada: 
https://github.com/ScalablyTyped/Converter/pull/473
I will now work on minimizing it

**Comment by lgirault** [comment]
done ! this was way easier than initially thought.
