### ISSUE TITLE
StackOverflowError generating types for openlayers 7.1.0

### ISSUE THREAD

**Issue by minettiandrea** [ScalablyTyped/Converter#483]
Hello,
first of all thank you for the great tool, I'm opening a new issue because  I'm trying to convert ol (https://www.npmjs.com/package/ol) with
```
sbt-converter 1.0.0-beta39
Scala 2.13.9
"ol" -> "7.1.0"
```

But the converter crashes with a StackOverflowError:
```
[warn] ReplaceExports.scala:55  Dropping unexpected export in namespace TsExport(NoComments,false,Named,Names(IArray((TsQIdent(IArray(TsIdentSimple(FLOAT))),None)),None)) [thread => 146, project => oltest, ms => 6364, phase => typescript, scope => TreeScope(TsParsedFile() / TsDeclModule(ol/webgl/Helper) / TsDeclNamespace(AttributeType)), id => ol]
[error] PhaseRes.scala:81  StackOverflowError [thread => 146, project => oltest, ms => 14964, phase => typescript, id => ol]java.lang.StackOverflowError
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$.search(TsTreeScope.scala:451)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.local$1(TsTreeScope.scala:349)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.lookupImpl(TsTreeScope.scala:420)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupInternal(TsTreeScope.scala:111)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupInternal$(TsTreeScope.scala:89)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.lookupInternal(TsTreeScope.scala:277)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$.$anonfun$search$4(TsTreeScope.scala:507)
[error] 	at org.scalablytyped.converter.internal.IArray.map(IArray.scala:491)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$.search(TsTreeScope.scala:478)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.local$1(TsTreeScope.scala:349)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.lookupImpl(TsTreeScope.scala:420)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupInternal(TsTreeScope.scala:110)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupInternal$(TsTreeScope.scala:89)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.lookupInternal(TsTreeScope.scala:277)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupBase(TsTreeScope.scala:78)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupBase$(TsTreeScope.scala:70)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.lookupBase(TsTreeScope.scala:277)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupType(TsTreeScope.scala:62)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope.lookupType$(TsTreeScope.scala:61)
[error] 	at org.scalablytyped.converter.internal.ts.TsTreeScope$Scoped.lookupType(TsTreeScope.scala:277)
[error] 	at org.scalablytyped.converter.internal.ts.transforms.DefaultedTypeArguments$.enterTsTypeRef(DefaultedTypeArguments.scala:24)
[error] 	at org.scalablytyped.converter.internal.ts.transforms.DefaultedTypeArguments$.enterTsTypeRef(DefaultedTypeArguments.scala:20)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation$$anon$1.enterTsTypeRef(TreeTransformation.scala:729)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation$$anon$1.enterTsTypeRef(TreeTransformation.scala:729)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsTypeRef(TreeTransformation.scala:456)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsTypeRef$(TreeTransformation.scala:455)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation$$anon$1.visitTsTypeRef(TreeTransformation.scala:627)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsType(TreeTransformation.scala:583)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsType$(TreeTransformation.scala:568)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation$$anon$1.visitTsType(TreeTransformation.scala:627)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.$anonfun$visitTsTypeRef$1(TreeTransformation.scala:459)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsTypeRef(TreeTransformation.scala:459)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsTypeRef$(TreeTransformation.scala:455)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation$$anon$1.visitTsTypeRef(TreeTransformation.scala:627)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsType(TreeTransformation.scala:583)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsType$(TreeTransformation.scala:568)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation$$anon$1.visitTsType(TreeTransformation.scala:627)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.$anonfun$visitTsTypeRef$1(TreeTransformation.scala:459)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsTypeRef(TreeTransformation.scala:459)
[error] 	at org.scalablytyped.converter.internal.ts.TreeTransformation.visitTsTypeRef$(TreeTransformation.scala:455)

```

I've created a simple project to replicate the issue:
https://github.com/minettiandrea/scalablytyped-ol-test

Not sure if it's related to #412

**Comment by oyvindberg** [comment]
Thanks! There are quite a few opportunities for this to happen unfortunately, but I'll tackle this and that other issue together. Expect it to be some time before I get to this, short on time
