### ISSUE TITLE
sbt 1.9.x support

### ISSUE THREAD

**Issue by xerial** [ScalablyTyped/Converter#539]
sbt-coverter plugin fails when using sbt 1.9.x at this code:
https://github.com/ScalablyTyped/Converter/blob/3a4686a8ee2547478c12a30ee98ac7d8f12d0a65/sbt-converter/src/main/scala/org/scalablytyped/converter/plugin/ScalablyTypedPluginBase.scala#L114-L118

```
java.lang.RuntimeException: This version of the ScalablyTyped plugin only supports 1.8.x. You're currently using 1.9.0
	at scala.sys.package$.error(package.scala:30)
	at org.scalablytyped.converter.plugin.ScalablyTypedPluginBase$.$anonfun$globalSettings$2(ScalablyTypedPluginBase.scala:117)
```
sbt 1.9.0 is almost compatible with sbt 1.8.x, so this version check logic needs to be updated.

**Comment by xerial** [comment]
Created a PR #540 as a fix for this
